# Generated by Django 4.2 on 2023-04-28 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_published',
        ),
    ]
